baseURL = 'https://nick64.me/'
languageCode = 'en-us'
title = 'Nick64'

copyright = "© 2024 Nick64 oh wait i dont care"

theme = "SkY2K"
assetDir = "static"

[taxonomies]
	tag = "tags"
	
[params]
    dateFormat = "January 02, 2006"
	description = "A blog written by professional internet browser and self-certified awesome guy Nick64. Check him out!"
	sitename = "Nick64"
	ogimage = "images/profile.png"
	twitter = "@Nick64WasTaken"
	

[author]
	[author.nick64]
		name = "Nick64"
		email = "nick@nick64.me"
		twitter = "@Nick64WasTaken"
