baseURL = 'https://nick64.me/'
languageCode = 'en-us'
title = 'Nick64'

copyright = "2023 Nick64 oh wait i dont care"

theme = "YellowAndBlack"
canonifyURLs = true

[taxonomies]
	tag = "tags"
	
[params]
    dateFormat = "January 02, 2006"
	description = "A blog written by professional internet browser and self-certified awesome guy Nick64. Check him out!"
	sitename = "Nick64"
	ogimage = "images/gatoPfp.png"
	twitter = "@Nick64WasTaken"

[author]
	name = "Nick64"
	email = "nick@nick64.me"