baseURL = 'https://nick64.me/'
languageCode = 'en-us'
title = 'Nick64'

copyright = "2022 Nick64 oh wait i dont care"

theme = "YellowAndBlack"
canonifyURLs = true

[author]
	name = "Nick64"
	email = "nick@nick64.me"